# @package model

defaults:
  - common

name: ResNet3D18
module:
  _target_: models.ResNet3D18
  cache_folder: ${cache_folder}
  model_pretrained: true    # on Kinetics-400
  in_channels: 3
  out_channels: 1